// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfutsjcrrhrfcvvwtexy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmdXRzamNycmhyZmN2dnd0ZXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjI2MzgsImV4cCI6MjA3NDYzODYzOH0.FEsuBB9nisH43FlNRZFFhqJm_d-9SfI9tuNdBzMZ3AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});